# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_exp <- function(T, delta, X, lambda, a_0, b_0, a_omega, b_omega, m, s, g, maxiter, verbose) {
    .Call(`_survival_svb_fit_exp`, T, delta, X, lambda, a_0, b_0, a_omega, b_omega, m, s, g, maxiter, verbose)
}

fit_partial <- function(T, delta, X, lambda, a_0, b_0, m, s, g, maxiter, tol, verbose) {
    .Call(`_survival_svb_fit_partial`, T, delta, X, lambda, a_0, b_0, m, s, g, maxiter, tol, verbose)
}

construct_risk_set <- function(T, delta) {
    .Call(`_survival_svb_construct_risk_set`, T, delta)
}

log_likelihood <- function(b, X, R, F) {
    .Call(`_survival_svb_log_likelihood`, b, X, R, F)
}

