# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

opt_par_mu <- function(sigma, lambda, P, x_j, delta_ord) {
    .Call(`_survival_svb_opt_par_mu`, sigma, lambda, P, x_j, delta_ord)
}

opt_par_sig <- function(mu, lambda, P, x_j, delta_ord) {
    .Call(`_survival_svb_opt_par_sig`, mu, lambda, P, x_j, delta_ord)
}

opt_par_gam <- function(mu, sigma, lambda, a_0, b_0, P, x_j, delta_ord) {
    .Call(`_survival_svb_opt_par_gam`, mu, sigma, lambda, a_0, b_0, P, x_j, delta_ord)
}

fit_partial <- function(T, delta, X, lambda, a_0, b_0, m, s, g, maxiter, tol, verbose) {
    .Call(`_survival_svb_fit_partial`, T, delta, X, lambda, a_0, b_0, m, s, g, maxiter, tol, verbose)
}

normal_mgf <- function(x, m, s) {
    .Call(`_survival_svb_normal_mgf`, x, m, s)
}

log_normal_mgf <- function(x, m, s) {
    .Call(`_survival_svb_log_normal_mgf`, x, m, s)
}

sigmoid <- function(x) {
    .Call(`_survival_svb_sigmoid`, x)
}

init_log_P <- function(X, m, s, g) {
    .Call(`_survival_svb_init_log_P`, X, m, s, g)
}

order_T <- function(T) {
    .Call(`_survival_svb_order_T`, T)
}

order_delta <- function(T, delta) {
    .Call(`_survival_svb_order_delta`, T, delta)
}

log_likelihood <- function(b, X, T, delta) {
    .Call(`_survival_svb_log_likelihood`, b, X, T, delta)
}

